"""Versioned starter directory. Verification is per entry and scope, never inherited."""
VERSION=1
CHECKED='2026-10-05'
ENTRIES=[]
def add(id,name,url,kind='provider',provider='',geo=(),types=(),dates=(),cap=('catalog',),access=('unknown',),description='',checked=False,limitations='',overlap='',repo_type=''):
    ENTRIES.append(dict(id=id,name=name,url=url,kind=kind,provider=provider,description=description or name,geography=list(geo),historical_jurisdictions=[],dates=list(dates),gaps=[],languages=['English'] if geo and all('United States' in g for g in geo) else [],writing_systems=[],record_types=list(types),capabilities=list(cap),evidence_forms=['unknown'],access={'search':list(access),'images':['unknown'],'copies':['unknown']},integration='outbound link',rights='Unknown; check provider terms. Viewing does not grant redistribution rights.',verification='coverage checked' if checked else 'Needs verification',last_checked=CHECKED if checked else None,verification_source=url if checked else '',verification_scope=['link','stated description','stated coverage'] if checked else [],link_health='available' if checked else 'unknown',limitations=limitations or 'Check locality, indexing, digitization and image-access restrictions before drawing conclusions.',overlap_group=overlap,repository_type=repo_type,archived=False))
PROVIDERS=[
('familysearch','FamilySearch','https://www.familysearch.org/en/search/'),('ancestry','Ancestry Card Catalog','https://www.ancestry.com/search/collections/catalog'),('myheritage','MyHeritage historical records','https://www.myheritage.com/research'),('findmypast','Findmypast','https://www.findmypast.com/'),('nara','U.S. National Archives','https://www.archives.gov/research/genealogy'),('american-ancestors','American Ancestors','https://www.americanancestors.org/'),('findagrave','Find a Grave','https://www.findagrave.com/'),('blm','Bureau of Land Management','https://www.blm.gov/services/land-records/glo'),('loc','Library of Congress','https://www.loc.gov/collections/chronicling-america/'),('newspaperarchive','NewspaperArchive','https://newspaperarchive.com/'),('dpla','Digital Public Library of America','https://dp.la/'),('cyndi','Cyndi’s List','https://www.cyndislist.com/'),('tna','The National Archives — England & Wales','https://www.nationalarchives.gov.uk/'),('freebmd','FreeBMD','https://www.freebmd.org.uk/'),('freecen','FreeCEN','https://www.freecen.org.uk/'),('freereg','FreeREG','https://www.freereg.org.uk/'),('scotland','Scotland’s People','https://www.scotlandspeople.gov.uk/'),('irishgenealogy','IrishGenealogy','https://www.irishgenealogy.ie/'),('ireland','National Archives of Ireland','https://nationalarchives.ie/'),('canada','Library and Archives Canada','https://www.canada.ca/en/library-archives.html'),('trove','Trove — Australia','https://trove.nla.gov.au/'),('nzlibrary','National Library of New Zealand','https://natlib.govt.nz/'),('paperspast','Papers Past','https://paperspast.natlib.govt.nz/'),('nzarchives','Archives New Zealand','https://www.archives.govt.nz/'),('norway','Digitalarkivet — Norway','https://www.digitalarkivet.no/en/'),('archion','Archion','https://www.archion.de/en/'),('matricula','Matricula','https://data.matricula-online.eu/en/'),('geneanet','Geneanet','https://en.geneanet.org/'),('jewishgen','JewishGen','https://www.jewishgen.org/')]
for id,name,url in PROVIDERS:add(id,name,url)
for id,name,url,cap in [('fs-index','Historical record search','https://www.familysearch.org/en/search/','name index'),('fs-fulltext','Full-Text Search','https://www.familysearch.org/en/search/full-text','full text'),('fs-catalog','FamilySearch Catalog','https://www.familysearch.org/en/search/catalog','catalog'),('fs-wiki','FamilySearch Research Wiki','https://www.familysearch.org/en/wiki/Main_Page','guidance')]:add(id,name,url,'guidance','familysearch',cap=(cap,),access=('free account',))
US=('United States',);MA=('Massachusetts, United States',);NH=('New Hampshire, United States',);VT=('Vermont, United States',)
for id,name,geo,types,ranges,checked,lim in [
('1928860','Massachusetts, State Vital Records, 1638–1927',MA,('birth','marriage','death','vital'),((1638,1927),),True,'Title range is broad; component coverage varies. Amendments and delayed registrations are included. Check actual locality and year.'),
('1463156','Massachusetts Deaths, 1841–1915, 1921–1924',MA,('death','vital'),((1841,1915),(1921,1924)),True,'Gap 1916–1920 in stated title; image restrictions must be checked.'),
('2106411','Massachusetts Land Records, 1620–1986',MA,('land','deed'),((1620,1986),),False,'Browsable collection; county and volume coverage needs verification.'),
('1542861','New Hampshire, Birth Records, Early to 1900',NH,('birth','vital'),((None,1900),),True,'Index cards; assess the underlying record and informant.'),
('1520640','New Hampshire, Marriage Records, 1637–1947',NH,('marriage','vital'),((1637,1947),),True,''),
('1784223','Vermont, Vital Records, 1760–1954',VT,('birth','marriage','death','vital'),((1760,1954),),True,'Town-clerk transcriptions; availability differs by town and year. Not all cards derive from original town records.'),
('1987653','Vermont, Town Clerk, Vital and Town Records, 1732–2005',VT,('vital','birth','marriage','death'),((1732,2005),),True,''),
('1803959','United States Census, 1790',US,('census',),((1790,1790),),False,'Name index and household schedules; verify coverage.')]:
    add('fs-'+id,name,'https://www.familysearch.org/en/search/collection/'+id,'collection','familysearch',geo,types,ranges,('name index','browse images'),('free account',),checked=checked,limitations=lim,overlap='ma-vitals' if id in ('1928860','1463156') else '')
for id,name,url,types,ranges,checked in [
('loc-news','Chronicling America','https://www.loc.gov/collections/chronicling-america/',('newspaper','obituary','marriage','legal notice'),(),False),
('loc-sanborn','Sanborn Maps','https://www.loc.gov/collections/sanborn-maps/',('land','residence'),(),False),
('loc-war','Civil War Maps','https://www.loc.gov/collections/civil-war-maps/',('military','land'),(),False)]:add(id,name,url,'collection','loc',US,types,ranges,('full text','browse images'),('free',),checked=checked)
add('nara-1950','1950 U.S. Census','https://www.archives.gov/research/census/1950','collection','nara',US,('census',),((1950,1950),),('name index','browse images'),('free',),checked=True,limitations='OCR name indexing can miss names. Browse enumeration districts when necessary.')
add('nara-freedmen','Freedmen’s Bureau records','https://www.archives.gov/research/african-americans/freedmens-bureau','collection','nara',US,('marriage','employment','court','school'),((1865,1872),),('catalog','browse images','request'),checked=True,limitations='Coverage varies by office and series. Use the official guide to identify applicable records.')
add('blm-patents','Federal land patents','https://www.blm.gov/services/land-records/glo','collection','blm',US,('land','grant'),cap=('name index','browse images'),checked=True,limitations='Federal public-land records; not a general index of private deeds or all states.')
add('ma-archives','Massachusetts Archives','https://www.sec.state.ma.us/divisions/archives/research/family-history.htm','repository','ma-archives',MA,('vital','census','migration','probate'),cap=('catalog','onsite','request'),checked=True,repo_type='state archives')
add('ma-vitals','Massachusetts Archives vital records, 1841–1935','https://www.sec.state.ma.us/divisions/archives/collections/vital-records.htm','collection','ma-archives',MA,('birth','marriage','death','vital'),((1841,1935),),('request','browse images'),('free','paid retrieval'),checked=True,overlap='ma-vitals',limitations='Digital coverage is incomplete, especially recent transfers. Certified copies have separate conditions. Pre-1841 records are held by towns.')
add('fitchburg','Fitchburg Public Library','https://fitchburgma.gov/279/Genealogy','repository','fitchburg',('Fitchburg, Massachusetts, United States',),('newspaper','yearbook','directory'),cap=('onsite','catalog'),access=('library access',),checked=True,repo_type='public library',limitations='Ancestry Library Edition is in-library only; individual digital collections have their own access rules.')
for id,name,types,dates in [('fitch-yearbook','Fitchburg High School — The Boulder',('yearbook',),((1897,2023),)),('fitch-bernard','St. Bernard’s High School — The Bernardian',('yearbook',),((1929,2023),)),('fitch-obit','FPL Sentinel & Enterprise obituary index',('obituary','newspaper'),())]:add(id,name,'https://fitchburgma.gov/279/Genealogy','collection','fitchburg',('Fitchburg, Massachusetts, United States',),types,dates,('browse images',),('unknown',),checked=True,limitations='Open the library page and select this named collection; links are not parameterized searches.')
add('nh-vitals','New Hampshire Vital Records Administration','https://sos.nh.gov/archives-vital-records-records-management/vital-records-information/vital-records-administration','repository','nh-vitals',NH,('vital',),cap=('onsite','request'),repo_type='state archives',limitations='Official check blocked (503) on 2026-10-05; access and holdings need review.')
add('nashua','Nashua Public Library','https://www.nashualibrary.org/230/Local-History-and-Genealogy','repository','nashua',('Nashua, New Hampshire, United States',),('newspaper','directory'),cap=('catalog','onsite'),checked=True,repo_type='public library')
add('nashua-news','Nashua newspaper archives','https://www.nashualibrary.org/230/Local-History-and-Genealogy','collection','nashua',('Nashua, New Hampshire, United States',),('newspaper','obituary'),((1869,None),),('full text',),('library access',),checked=True,limitations='Library describes newspaper access from 1869; title gaps and eligibility require checking.')
add('vt-archives','Vermont State Archives and Records Administration','https://sos.vermont.gov/vsara/learn/state-vital-records-registry','repository','vt-archives',VT,('vital','court','probate'),cap=('catalog','onsite','request'),repo_type='state archives',limitations='Official check blocked (403) on 2026-10-05. Verify holdings and access.')
add('vhs','Vermont Historical Society — Leahy Library','https://vermonthistory.org/genealogy','repository','vhs',VT,('family history','local history','manuscript'),cap=('catalog','onsite','request'),checked=True,repo_type='historical society',limitations='Not the repository for Vermont vital records or newspapers; use its genealogical and manuscript holdings.')
add('vhs-manuscripts','Vermont Historical Society manuscripts','https://vermonthistory.org/manuscripts','collection','vhs',VT,('manuscript','family history','migration'),cap=('catalog','onsite'),checked=True)
add('worcester-deeds','Worcester Registry of Deeds','https://www.masslandrecords.com/Worcester/','repository','worcester-deeds',('Worcester, Massachusetts, United States',),('land','deed'),cap=('name index','request'),repo_type='registry of deeds')
add('nh-history','New Hampshire Historical Society','https://www.nhhistory.org/','repository','nh-history',NH,('manuscript','local history'),cap=('catalog','onsite','request'),repo_type='historical society')
add('ma-probate','Massachusetts Probate and Family Court','https://www.mass.gov/orgs/probate-and-family-court','repository','ma-probate',MA,('probate','will','guardianship'),cap=('request','onsite'),repo_type='probate court')
add('boston-archdiocese','Archives of the Archdiocese of Boston','https://www.bostoncatholic.org/archives','repository','boston-archdiocese',MA,('religious','baptism','marriage'),cap=('request',),repo_type='religious archives')
add('nashua-clerk','Nashua City Clerk — genealogy research','https://www.nashuanh.gov/207/Genealogy-Research','repository','nashua-clerk',('Nashua, New Hampshire, United States',),('vital',),cap=('request','onsite'),repo_type='town clerk')
PATHWAYS=[
('african-american','African American research','https://www.archives.gov/research/african-americans','Start with known people, places and dates; consult Freedmen’s Bureau field-office records and trace households across emancipation. Do not infer identity from a name.'),
('indigenous','Indigenous research','https://www.archives.gov/research/native-americans','Identify the relevant nation and jurisdiction from evidence; consult tribal and federal guidance. Archival records do not establish tribal citizenship.'),
('adoption','Adoption research','https://www.childwelfare.gov/topics/adoption/search/','Begin with consent and the relevant jurisdiction’s official access guidance. Records may be restricted; do not assume public access.'),
('displacement','Displacement research','https://www.ushmm.org/online/hsv/','Trace places and name variants across displacement; consult the Holocaust Survivors and Victims Database for relevant contexts, with sensitivity to living people.'),
('migration','Migration research','https://www.archives.gov/research/immigration','Work backward from the destination using passenger and naturalization records; compare original-language names and historical jurisdictions.')]
for id,name,url,description in PATHWAYS:add('path-'+id,name,url,'guidance',description=description)

# Verification amendments from official pages inspected 2026-10-05.
# Homepage availability is deliberately only a link check, never inherited by collections.
VERSION=2
_link_checked={'familysearch','ancestry','myheritage','nara','american-ancestors','blm','newspaperarchive','cyndi','freebmd','freereg','scotland','irishgenealogy','ireland','canada','nzarchives','norway','archion','matricula','geneanet','jewishgen','fs-index','fs-catalog','fs-fulltext'}
_blocked={'findmypast','findagrave','loc','dpla','tna','freecen','trove','nzlibrary','paperspast','fs-wiki','nh-vitals','vt-archives','nh-history','ma-probate','loc-news','loc-sanborn','loc-war','path-displacement','path-adoption'}
for entry in ENTRIES:
    if entry['id'] in _link_checked:
        entry.update(last_checked=CHECKED,verification='link checked',verification_source=entry['url'],verification_scope=['link availability; no collection-level access validation'],link_health='available')
    if entry['id'] in _blocked:
        entry.update(last_checked=CHECKED,verification='Needs verification',verification_source=entry['url'],verification_scope=['Attempted official-page check; blocked, unavailable, or insufficient rendered content'],link_health='unknown',maintenance_notes='Check attempted 2026-10-05. Automated access was inconclusive; not evidence that the resource is broken.')
    if entry['id'] in {'worcester-deeds','boston-archdiocese','nashua-clerk'}:
        entry.update(last_checked=CHECKED,verification='coverage checked',verification_source=entry['url'],verification_scope=['link availability','repository identity and stated services'],link_health='available')
    if entry['id']=='worcester-deeds':
        entry['access']={'search':['free'],'images':['free'],'copies':['free']};entry['verification_scope'].append('stated search, viewing and download access')
    if entry['id'] in {'path-african-american','path-indigenous','path-migration'}:
        entry.update(last_checked=CHECKED,verification='coverage checked',verification_source=entry['url'],verification_scope=['official guidance reviewed'],link_health='available',capabilities=['guidance'])
    if entry['id']=='path-adoption':
        entry.update(url='https://www.sec.state.ma.us/divisions/archives/research/family-history.htm',description='Massachusetts starting point: distinguish recorded legal adoption from informal care. Use the relevant court or archive’s access guidance; records may be restricted.',verification='coverage checked',verification_source='https://www.sec.state.ma.us/divisions/archives/research/family-history.htm',verification_scope=['Official Adoptions guidance section reviewed'],link_health='available',geography=list(MA),capabilities=['guidance'])
    if entry['id']=='fs-2106411':entry['capabilities']=['browse images'];entry['evidence_forms']=['original document image']
    if entry['id']=='fs-1928860':
        entry['dates']=[[1841,1920],[1915,1925]];entry['limitations']='Collection title includes 1638–1927, but official description specifies amendments 1841–1920 and births/marriages/deaths 1915–1925. Actual locality, year and image eligibility require inspection.'
    if entry['id']=='fitch-obit':entry['capabilities']=['name index'];entry['evidence_forms']=['index']
    if entry['id'] in {'loc-sanborn','loc-war'}:entry['capabilities']=['catalog','browse images']
    if entry['provider']=='familysearch' and entry['kind']=='collection':entry['access']['images']=['free account','possible onsite restrictions'];entry['evidence_forms']=['index','original document image']
add('uvm','University of Vermont — Silver Special Collections','https://digitalcollections.uvm.edu/','repository','uvm',VT,('manuscript','local history','military'),cap=('catalog','full text'),checked=True,repo_type='university special collections',limitations='Digital subset of the library’s holdings; broader onsite holdings and access require consultation.')
add('ma-passengers','Boston passenger lists, 1848–1891','https://www.sec.state.ma.us/divisions/archives/research/family-history.htm','collection','ma-archives',MA,('migration','passenger'),((1848,1891),),('name index','request'),checked=True,limitations='State Port of Boston records; indexing is incomplete. Open the Passenger Lists section.')
add('ma-state-census','Massachusetts state census schedules, 1855 & 1865','https://www.sec.state.ma.us/divisions/archives/research/family-history.htm','collection','ma-archives',MA,('census',),((1855,1855),(1865,1865)),('browse images','onsite'),checked=True)
add('ma-suffolk-deeds','Suffolk County deeds, 1629–1800','https://www.sec.state.ma.us/divisions/archives/research/family-history.htm','collection','ma-archives',('Suffolk, Massachusetts, United States',),('land','deed'),((1629,1800),),('browse images','request'),checked=True)
add('freebmd-index','England & Wales civil registration index','https://www.freebmd.org.uk/','collection','freebmd',('England','Wales'),('birth','marriage','death','vital'),((1837,1999),),('name index',),('free',),checked=True,limitations='Volunteer transcription remains incomplete; index entries are not certificates.')
# Types available for user-managed collections; fields never imply comprehensive seed coverage.
TAXONOMY={
'Vital and religious':['birth','baptism','marriage','banns','divorce','death','burial','religious','congregational register'],
'Households and residence':['census','population register','electoral roll','directory','address book'],
'Migration and citizenship':['migration','passenger','border crossing','passport','naturalization','citizenship'],
'Property and courts':['deed','grant','mortgage','tax','will','probate','guardianship','court'],
'Military':['service','pension','draft','muster','casualty'],
'Newspapers':['obituary','announcement','legal notice','social column','missing-person notice'],
'Community and institutions':['school','yearbook','employment','poor relief','institutional register'],
'Published research':['family history','local history','journal','biography','transcription'],
'Archival discovery':['finding aid','manuscript','catalog','onsite'],
'Family-contributed material':['tree','letter','diary','photograph','oral history']}

# Final verification additions, 2026-10-05. Access is scoped to the stated route.
VERSION=3
add('fs-worcester-probate','Massachusetts, Worcester County, Probate Files, 1731–1925','https://www.familysearch.org/en/search/collection/2102083','collection','familysearch',('Worcester, Massachusetts, United States',),('probate','will','guardianship'),((1731,1925),),('browse images',),('free account',),checked=True,limitations='Image publication remains incremental. Browse file numbers and surnames; image eligibility may depend on account/location.')
ENTRIES[-1]['access']['images']=['free account','possible onsite restrictions']
ENTRIES[-1]['evidence_forms']=['original document image']
add('boston-sacraments','Boston Archdiocese sacramental records, 1789–1920','https://bostoncatholic.org/digital-collections','collection','american-ancestors',MA,('baptism','marriage','religious'),((1789,1920),),('browse images','name index'),('free account','subscription'),checked=True,limitations='Official archive page links to two databases: guest-account image browsing and member-only name searching. Parish/year digitization is incomplete.',overlap='boston-sacraments')
ENTRIES[-1]['access']={'search':['subscription'],'images':['free account'],'copies':['unknown']}
ENTRIES[-1]['verification_scope']=['official archive collection description','stated guest browsing and membership search routes']
ENTRIES[-1]['evidence_forms']=['original document image','index']
for entry in ENTRIES:
    if entry['id']=='path-displacement':
        url='https://text-message.blogs.archives.gov/2022/01/27/state-records-relating-to-refugees-displaced-persons-relief-and-war-crimes-during-wwii-era-part-1/'
        entry.update(url=url,provider='nara',description='World War II displacement starting point: NARA guidance to State Department refugee/relief files and finding aids. Establish the person’s route and dates before choosing a series; this is not a comprehensive name index.',verification='coverage checked',last_checked=CHECKED,verification_source=url,verification_scope=['official archivist guidance and described finding aids'],link_health='available',capabilities=['guidance'],geography=[],dates=[],limitations='Primarily World War II era government records. Individual-file availability and privacy restrictions require archive review.')
